CAD: room1.cad
description: This is a super duper stud welding mission
last_saved: 1435740118.2856705
name: configured
state: 4
tasks:
  task_1:
    nav_goal: {x: 236.78, y: 364.74, yaw: 1.24}
    state: 4
    stud_pattern: {distance: 300.0, distribution: some_dist, press: 50.0, proximity: 150.0}
    stud_type: type57
    studs:
      stud_1: {state: 0, time_stamp: 1435592983.446101, x: 0.15, y: 0.15}
      stud_2: {state: 0, time_stamp: 1435592983.4654157, x: 0.25, y: 0.15}
      stud_3: {state: 0, time_stamp: 1435592983.4878109, x: 0.15, y: 0.25}
      stud_4: {state: 0, time_stamp: 1435592983.5076973, x: 0.25, y: 0.25}
  task_2:
    nav_goal: {x: 896.78, y: 484.74, yaw: 1.24}
    state: 4
    stud_pattern: {distance: 400.0, distribution: some_dist, press: 50.0, proximity: 125.0}
    stud_type: type89
    studs:
      stud_1: {state: 0, time_stamp: 1435592986.5076993, x: 0.15, y: 0.15}
      stud_2: {state: 0, time_stamp: 1435592986.5250776, x: 0.25, y: 0.15}
      stud_3: {state: 0, time_stamp: 1435592986.5436993, x: 0.15, y: 0.25}
      stud_4: {state: 0, time_stamp: 1435592986.5660121, x: 0.25, y: 0.25}
  task_3:
    nav_goal: {x: 916.78, y: 374.74, yaw: 1.24}
    state: 4
    stud_pattern: {distance: 150.0, distribution: some_dist, press: 50.0, proximity: 250.0}
    stud_type: type31
    studs:
      stud_1: {state: 0, time_stamp: 1435592989.0703263, x: 0.15, y: 0.15}
      stud_2: {state: 0, time_stamp: 1435592989.0923676, x: 0.25, y: 0.15}
      stud_3: {state: 0, time_stamp: 1435592989.112519, x: 0.15, y: 0.25}
      stud_4: {state: 0, time_stamp: 1435592989.136413, x: 0.25, y: 0.25}
  task_4:
    nav_goal: {x: 24.78, y: 672.74, yaw: 1.24}
    state: 4
    stud_pattern: {distance: 250.0, distribution: some_dist, press: 50.0, proximity: 100.0}
    stud_type: type49
    studs:
      stud_1: {state: 0, time_stamp: 1435592991.5127034, x: 0.15, y: 0.15}
      stud_2: {state: 0, time_stamp: 1435592991.5291295, x: 0.25, y: 0.15}
      stud_3: {state: 0, time_stamp: 1435592991.5509257, x: 0.15, y: 0.25}
      stud_4: {state: 0, time_stamp: 1435592991.5704656, x: 0.25, y: 0.25}
