CAD: room1.cad
description: This is a super duper stud welding mission
last_saved: 1440432279.2166088
name: configured
state: 2
tasks:
  task_1:
    direction: 0
    nav_goal: {x: 236.78, y: 364.74, yaw: 1.24}
    state: 2
    stud_pattern: {distance: 300.0, distribution: some_dist, press: 50.0, proximity: 150.0}
    stud_type: type57
    voltage: 100.0
  task_2:
    direction: 0
    nav_goal: {x: 896.78, y: 484.74, yaw: 1.24}
    state: 2
    stud_pattern: {distance: 400.0, distribution: some_dist, press: 50.0, proximity: 125.0}
    stud_type: type89
    voltage: 100.0
  task_3:
    direction: 0
    nav_goal: {x: 916.78, y: 374.74, yaw: 1.24}
    state: 2
    stud_pattern: {distance: 150.0, distribution: '', press: 0.0, proximity: 0.0}
    stud_type: type89
    voltage: 100.0
  task_4:
    direction: 0
    nav_goal: {x: 24.78, y: 672.74, yaw: 1.24}
    state: 2
    stud_pattern: {distance: 100.0, distribution: 2-1-2, press: 0.0, proximity: 100.0}
    stud_type: M3x70
    voltage: 100.0
