CAD: room1.cad
name: configured
description: This is a super duper stud welding mission
last_saved: 1429631054.123456
state: 2
tasks:
  task_1:
    state: 2
    nav_goal: {x: 236.78, y: 364.74, yaw: 1.24}
    stud_pattern: {distance: 300.0, distribution: some_dist, proximity: 150.0}
    stud_type: type57
  task_2:
    state: 2
    nav_goal: {x: 896.78, y: 484.74, yaw: 1.24}
    stud_pattern: {distance: 400.0, distribution: some_dist, proximity: 125.0}
    stud_type: type89
  task_3:
    state: 2
    nav_goal: {x: 916.78, y: 374.74, yaw: 1.24}
    stud_pattern: {distance: 150.0, distribution: some_dist, proximity: 250.0}
    stud_type: type31
  task_4:
    state: 2
    nav_goal: {x: 24.78, y: 672.74, yaw: 1.24}
    stud_pattern: {distance: 250.0, distribution: some_dist, proximity: 100.0}
    stud_type: type49
