
---
mission_control/ParamString distributions
mission_control/ParamString stud_types
mission_control/ParamDouble force
mission_control/ParamDouble distance
mission_control/ParamDouble proximity
mission_control/ParamDouble power
bool success
string message

